//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityAspProject.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sale
    {
        public int sal_id { get; set; }
        public Nullable<int> sal_prd { get; set; }
        public Nullable<byte> sal_stf { get; set; }
        public Nullable<int> sal_ctm { get; set; }
        public Nullable<decimal> sal_price { get; set; }
        public Nullable<bool> sal_status { get; set; }
    
        public virtual tbl_customer tbl_customer { get; set; }
        public virtual tbl_product tbl_product { get; set; }
        public virtual tbl_staff tbl_staff { get; set; }
    }
}
